{{--
    Site search powered by Pagefind (https://pagefind.app). The /pagefind/
    bundle is generated by `php artisan site:build` for sites with
    'search' => true, and served statically by Caddy. Until the first build
    runs (e.g. plain local dev), the page shows a friendly fallback.

    data-pagefind-ignore keeps the search page itself out of the index.
--}}
@extends('site::layout')

@section('site-content')
<div data-pagefind-ignore>
    <h1>{{ __('Search') }}</h1>

    <link href="/pagefind/pagefind-ui.css" rel="stylesheet">
    <script src="/pagefind/pagefind-ui.js"></script>

    <div id="search"></div>

    <script>
        window.addEventListener('DOMContentLoaded', function () {
            if (window.PagefindUI) {
                new PagefindUI({
                    element: '#search',
                    showSubResults: true,
                    showImages: false,
                });
            } else {
                document.getElementById('search').innerHTML =
                    '<p>{{ __('Search becomes available after the first site build.') }}</p>';
            }
        });
    </script>
</div>
@endsection
